chore: updates example for latest stack schema
cloudposse/terraform-spacelift-cloud-infrastructure-automation pull request #20
Opened 2021-04-09 17:31 UTC by Gowiem

## what
* I'm starting to POC Spacelift and this module for a client, so figured I'd the following updated: 
  * Updates stack example to utilize all `spacelift.setting` + explains them. Utilizes the correct location as well. 
  * Updates surrounding documentation to talk about stacks more and link out to our docs. 
  * Provides some context around `imports` + `globals.yaml`
  * Fixes usage of `components.globals` to utilize newer top-level `vars`

## why
* Keeps documentation up-to-date

2021-04-09 17:33 UTC, Gowiem commented
/test all

2021-04-09 17:47 UTC, Gowiem commented
/test all

2021-04-09 22:52 UTC, Nuru requested changes
Most of this documentation probably belongs in [terraform-yaml-stack-config](https://github.com/cloudposse/terraform-yaml-stack-config) and/or [atmos](https://github.com/cloudposse/atmos), but as long as you are adding it here, please also document how to configure a virtual component.

```yaml
components:
  terraform:
    another-first-component:
      component: first-component
      vars:
        my_input_var: "Hello world! This is a value that needs to be passed to my `first-component` Terraform component."
```

2021-04-10 16:18 UTC, Gowiem commented
@Nuru yeah I don't like that we have to define stack configurations in multiple locations, so I've opened https://github.com/cloudposse/docs/pull/536 to deal with that.

2021-04-10 18:12 UTC, osterman approved these changes

2021-04-10 19:20 UTC, Gowiem commented
@osterman I actually want to close this PR in favor of a new one after https://github.com/cloudposse/docs/pull/536 gets merged. Let me know your thoughts in that PR.

2021-04-16 17:19 UTC, Gowiem commented
Closing as https://github.com/cloudposse/docs/pull/536 will supersede. I'll put up a follow up PR after that merges.

2021-04-16 17:19 UTC, closed without merging