feat: adds global access policy +  adds override vars for existing pols
cloudposse/terraform-spacelift-cloud-infrastructure-automation pull request #38
Opened 2021-06-10 04:53 UTC by Gowiem

## what
* Adds `access-global.rego` + attachment to all automated stacks
* Adds `*_policy_id_override` variables for overriding the module's policies

## why
* By default, Spacelift does not provide access for normal users to any stacks. [Access Policies](https://docs.spacelift.io/concepts/policy/stack-access-policy) need to be attached to stacks to grant access. The `access-global.rego` policy provides `write` access to all users by default. 
* The override policy ID vars provide more flexibility in case any module consumers want to customize their stack policies beyond what the module provides by default. 

## references
* N/A

2021-06-10 04:54 UTC, Gowiem commented
/test all

2021-06-10 15:34 UTC, Gowiem commented
/test terratest

2021-06-14 15:12 UTC, Gowiem commented
@aknysh @osterman getting the below for the terratests on this module. Seems API keys are not being passed to the `provider` block, but that has been happening consistently for a while now. Do we not have a test spacelift account for this module? Anything blocking a review here?

2021-06-14 19:52 UTC, aknysh commented
> @aknysh @osterman getting the below for the terratests on this module. Seems API keys are not being passed to the `provider` block, but that has been happening consistently for a while now. Do we not have a test spacelift account for this module? Anything blocking a review here?

We don't require Terratest to pass on this module since we don't have a testing Spacelift account yet

2021-06-14 20:04 UTC, Gowiem commented
@aknysh gotcha 👍

2021-06-14 20:20 UTC, Gowiem commented
/test all

2021-06-15 15:54 UTC, aknysh commented on variables.tf
> +variable "access_policy_id_override" {
```suggestion
variable "access_policy_id" {
```

@Gowiem thanks, it LGTM.
Maybe we don't need to use `_override`, it should be clear w/o it that we want to provide an existing policy

2021-06-15 15:54 UTC, aknysh commented on variables.tf
> +variable "push_policy_id_override" {
```suggestion
variable "push_policy_id" {
```

2021-06-15 15:54 UTC, aknysh commented on variables.tf
> +variable "plan_policy_id_override" {
```suggestion
variable "plan_policy_id" {
```

2021-06-15 15:54 UTC, aknysh commented on variables.tf
> +variable "trigger_policy_id_override" {
```suggestion
variable "trigger_policy_id" {
```

2021-06-15 15:55 UTC, aknysh commented on main.tf
> +  access_policy_id  = var.access_policy_id_override != null ? var.access_policy_id_override : spacelift_policy.access.id
```suggestion
  access_policy_id  = var.access_policy_id != null ? var.access_policy_id : spacelift_policy.access.id
```

2021-06-15 15:55 UTC, aknysh commented on main.tf
> +  push_policy_id    = var.push_policy_id_override != null ? var.push_policy_id_override : spacelift_policy.push.id
```suggestion
  push_policy_id    = var.push_policy_id != null ? var.push_policy_id : spacelift_policy.push.id
```

2021-06-15 15:55 UTC, aknysh commented on main.tf
> +  plan_policy_id    = var.plan_policy_id_override != null ? var.plan_policy_id_override : spacelift_policy.plan.id
```suggestion
  plan_policy_id    = var.plan_policy_id != null ? var.plan_policy_id : spacelift_policy.plan.id
```

2021-06-15 15:56 UTC, aknysh commented on main.tf
> +  trigger_policy_id = var.trigger_policy_id_override != null ? var.trigger_policy_id_override : spacelift_policy.trigger_dependency.id
```suggestion
  trigger_policy_id = var.trigger_policy_id != null ? var.trigger_policy_id : spacelift_policy.trigger_dependency.id
```

2021-06-15 15:59 UTC, aknysh commented on main.tf
> +  plan_policy_id    = var.plan_policy_id_override != null ? var.plan_policy_id_override : spacelift_policy.plan.id
also update all policies to not create them if we provide IDs of existing policies

```
resource "spacelift_policy" "plan" {  
  count = var.plan_policy_id == null ? 1 : 0
  
  type = "PLAN"  
  name = "Global Plan Policy"  
  body = file("${path.module}/policies/plan-global.rego")
}
```

2021-06-15 15:59 UTC, aknysh requested changes
thanks @Gowiem please see comments

2021-06-15 16:40 UTC, aknysh commented
@Gowiem  the PR looks good, we need many of the changes :)
I can hijack your PR to improve it and add some other features that we need now, if you don't mind.

2021-06-15 17:06 UTC, Gowiem commented
Good stuff @aknysh -- Let me know how I can help. I'm happy to review when you're finished up.

2021-06-15 17:37 UTC, Gowiem commented
/test all

2021-06-15 18:56 UTC, Gowiem commented
@aknysh ready to merge this or did you want to hold off for more changes that you wanted to make?

2021-06-15 19:09 UTC, aknysh commented
/test all

2021-06-15 19:13 UTC, aknysh approved these changes
thanks @Gowiem

2021-06-15 19:14 UTC, merged

2021-06-15 19:29 UTC, Gowiem commented
Much appreciated @aknysh!