Update example variables
cloudposse/terraform-spacelift-cloud-infrastructure-automation pull request #80
Opened 2022-01-03 19:05 UTC by max-lobur

## what
* Update example with current variables

## why
* Example refers deprecated vars

2022-01-03 19:18 UTC, aknysh commented on README.md
> -  stack_config_path          = var.stack_config_path
these are not needed

```
locals {
  config_filenames   = fileset(var.stack_config_path, "*.yaml")
  stack_config_files = [for f in local.config_filenames : f if(replace(f, "globals", "") == f)]
  stacks             = [for f in local.stack_config_files : trimsuffix(basename(f), ".yaml")]
}
```

2022-01-03 19:26 UTC, max-lobur commented on README.md
> -  stack_config_path          = var.stack_config_path
ah, right

2022-01-03 20:28 UTC, aknysh commented on README.yaml
> +    year: "2022"
no need to change it @max-lobur 
here, it's just the start year

2022-01-03 20:28 UTC, aknysh commented on README.yaml
> +    year: "2022"
```suggestion
    year: "2021"
```

2022-01-03 20:28 UTC, aknysh commented on README.yaml
> +    year: "2022"
otherwise, it will do 

```
Copyright © 2022-2022
```

2022-01-03 21:09 UTC, nitrocode approved these changes

2022-01-03 21:11 UTC, aknysh approved these changes

2022-01-31 07:32 UTC, max-lobur commented
/test all

2022-01-31 11:23 UTC, korenyoni commented
> /test all

@max-lobur Terratest isn't set up for this repo (we are missing valid API keys)

2022-01-31 11:27 UTC, korenyoni commented
Also please get rid of this variable 

```hcl
± |max-lobur-patch-1 ✓| → tflint --module --enable-rule=terraform_deprecated_index --enable-rule=terraform_unused_declarations --enable-rule=terraform_documented_outputs --enable-rule=terraform_required_providers --enable-rule=terraform_unused_required_providers
1 issue(s) found:

Warning: variable "external_execution" is declared but not used (terraform_unused_declarations)

  on variables.tf line 30:
  30: variable "external_execution" {

Reference: https://github.com/terraform-linters/tflint/blob/v0.27.0/docs/rules/terraform_unused_declarations.md
```

2022-01-31 11:27 UTC, korenyoni requested changes
Requested an unused variable to be removed as part of this PR

2022-01-31 12:14 UTC, max-lobur commented
@korenyoni https://github.com/cloudposse/terraform-spacelift-cloud-infrastructure-automation/blob/acd61c280a552a4dc8c7858b8338012790ff8661/main.tf#L109

2022-01-31 12:16 UTC, korenyoni commented
> @korenyoni
> 
> https://github.com/cloudposse/terraform-spacelift-cloud-infrastructure-automation/blob/acd61c280a552a4dc8c7858b8338012790ff8661/main.tf#L109

Weird, not sure why `tflint` didn't catch that

2022-01-31 12:16 UTC, korenyoni approved these changes
LGTM

2022-01-31 12:24 UTC, merged